### PR TITLE
Update channels.py to capture additional available channels

### PR DESCRIPTION
**Pull request by dubmn**
Updated search of DL channel lists to find individual lettered lists in order to capture all available channels.  Results nearly increased by 100 total.  Simply changed the original re.search to a re.findall and changed the regular expression to only get the individual lettered channels and not the incomplete "Full List" table.

### CODE REVIEW

**Comment by riyaaz2016** [comment]
Which additional channels can we now see/get?

**Comment by rocky4546** [comment]
Thanks for the PR.  Might be nice, in the future, if the additional USA channels might get their guide from tvguide.

**Comment by dubmn** [comment]
> Which additional channels can we now see/get?

The ones I was most looking for were the Bally Sports network or channels for local sports (Twins, Timberwolves, Wild here in Minnesota).  The others I noticed right off hand were some more movie channels like Showtime 2 and Showtime Showcase.  All in all it went from 682 channels to 752.  And 1/3 of them being US channels.

**Comment by dubmn** [comment]
> Thanks for the PR.  Might be nice, in the future, if the additional USA channels might get their guide from tvguide.
> 
> 

Yes I should have updated the channel_list.json and will soon enough.  I actually don't use the built in plugin but instead just output the m3u from Cabernet and have another container generating EPG from zap2xml.

**Comment by rocky4546** [comment]
I too use zap2xml.pl for EPG on my antenna.  Some point in the future, the plan is to also include a zap plugin so you can choose between TVG and ZAP. But for now, I have TVG working.  Hardest part in creating the TVG list is to know the provider and timezone of the channel in order to obtain the correct guide.  It looks like you may already have that info.

**Comment by Joshbloam** [comment]
> All in all it went from 682 channels to 752. And 1/3 of them being US channels.

Hi I updated the plugin and refreshed my channel list, but still shows 682 in total. How do I get the additional channels like Bally sports?

**Pull request merged**
